SOURCES += \
    ../src/control/control.cpp \
    ../src/control/dummy.cpp \
    ../src/control/proxy.cpp \
    ../src/control/wireframe.cpp \
    ../src/control/2d/point2d_control.cpp \
    ../src/control/2d/circle_control.cpp \
    ../src/control/2d/triangle_control.cpp \
    ../src/control/2d/text_control.cpp \
    ../src/control/2d/rectangle_control.cpp \
    ../src/control/3d/point3d_control.cpp \
    ../src/control/3d/sphere_control.cpp \
    ../src/control/3d/extrude_control.cpp \
    ../src/control/3d/cube_control.cpp \
    ../src/control/3d/cylinder_control.cpp \
    ../src/control/3d/cone_control.cpp \
    ../src/control/deform/attract_control.cpp \
    ../src/control/deform/repel_control.cpp \
    ../src/control/deform/scalex_control.cpp \
    ../src/control/deform/scaley_control.cpp \
    ../src/control/deform/scalez_control.cpp \
    ../src/control/transform/rotatex_control.cpp \
    ../src/control/transform/rotatey_control.cpp \
    ../src/control/transform/rotatez_control.cpp \
    ../src/control/transform/reflectx_control.cpp \
    ../src/control/transform/reflecty_control.cpp \
    ../src/control/transform/reflectz_control.cpp \
    ../src/control/transform/recenter_control.cpp \
    ../src/control/transform/translate_control.cpp \
    ../src/control/iterate/iterate2d_control.cpp \
    ../src/control/iterate/iterate_polar_control.cpp \

HEADERS += \
    ../src/control/control.h \
    ../src/control/dummy.h \
    ../src/control/proxy.h \
    ../src/control/wireframe.h \
    ../src/control/2d/point2d_control.h \
    ../src/control/2d/circle_control.h \
    ../src/control/2d/triangle_control.h \
    ../src/control/2d/text_control.h \
    ../src/control/2d/rectangle_control.h \
    ../src/control/3d/point3d_control.h \
    ../src/control/3d/sphere_control.h \
    ../src/control/3d/extrude_control.h \
    ../src/control/3d/cylinder_control.h \
    ../src/control/3d/cone_control.h \
    ../src/control/3d/cube_control.h \
    ../src/control/deform/attract_control.h \
    ../src/control/deform/repel_control.h \
    ../src/control/deform/scalex_control.h \
    ../src/control/deform/scaley_control.h \
    ../src/control/deform/scalez_control.h \
    ../src/control/transform/rotatex_control.h \
    ../src/control/transform/rotatey_control.h \
    ../src/control/transform/rotatez_control.h \
    ../src/control/transform/reflectx_control.h \
    ../src/control/transform/reflecty_control.h \
    ../src/control/transform/reflectz_control.h \
    ../src/control/transform/recenter_control.h \
    ../src/control/transform/translate_control.h \
    ../src/control/iterate/iterate2d_control.h \
    ../src/control/iterate/iterate_polar_control.h \
